# Generated by Django 4.1.3 on 2022-12-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apimodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('operator', models.CharField(max_length=50)),
            ],
        ),
    ]
